PRE (int const []){
#include "p1.maq"
} POS,
PRE (int const []){
#include "p2.maq"
} POS,
PRE (int const []){
#include "init.maq"
} POS,
PRE (int const []){
#include "ex1.maq"
} POS,
PRE (int const []){
#include "ex2.maq"
} POS,
PRE (int const []){
#include "ex3.maq"
} POS,
PRE (int const []){
#include "ex4.maq"
} POS,
PRE (int const []){
#include "ex5.maq"
} POS,
PRE (int const []){
#include "test1.maq"
} POS,
